// ============================================================
// BLUEPRINTS — Public Administration Blueprint
// ============================================================

import type { SolutionBlueprint } from './types';
import { BASE_BLUEPRINT } from './base-blueprint';

export const PUBLIC_ADMINISTRATION_BLUEPRINT: SolutionBlueprint = {
  ...BASE_BLUEPRINT,
  id: 'public-administration',
  name: 'Public Administration Data Governance',
  version: '1.0.0',
  description: 'Comprehensive data governance for public sector organizations with strict compliance requirements',
  sector: 'PUBLIC_ADMINISTRATION',
  targetOrganizationType: 'Government agencies, tax authorities, public services (e.g., AEAT reference)',
  status: 'ACTIVE',
  implementationLevel: 'IMPLEMENTED',
  objectives: [
    'Data inventory',
    'Metadata governance',
    'Sensitive data classification',
    'Lineage tracking',
    'Quality monitoring',
    'Policy compliance',
    'Human oversight',
    'Evidence collection',
    'Auditability',
    'Impact analysis',
    'Certification',
  ],
  enabledAgents: [
    'source-discovery-agent',
    'metadata-intelligence-agent',
    'schema-change-agent',
    'classification-agent',
    'classification-review-agent',
    'data-quality-agent',
    'lineage-agent',
    'impact-analysis-agent',
    'policy-agent',
    'evidence-agent',
    'audit-agent',
    'certification-agent',
  ],
  requiredAgents: [
    'source-discovery-agent',
    'metadata-intelligence-agent',
    'classification-agent',
    'classification-review-agent',
    'data-quality-agent',
    'lineage-agent',
    'impact-analysis-agent',
    'policy-agent',
    'evidence-agent',
    'audit-agent',
  ],
  optionalAgents: [
    'schema-change-agent',
    'certification-agent',
  ],
  policyProfile: {
    enabledPolicies: [
      'PII_REQUIRES_REVIEW',
      'LOW_QUALITY_REQUIRES_REVIEW',
      'MISSING_LINEAGE_WARNING',
      'PUBLIC_DATA_COMPLIANCE',
      'SENSITIVE_DATA_RESTRICTION',
    ],
    enforcementLevel: 'PREPARED',
  },
  classificationProfile: {
    priorityClassifications: ['PII', 'PHI', 'CONFIDENTIAL', 'RESTRICTED', 'IDENTIFIER'],
    sensitivityLevels: ['PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED'],
  },
  qualityProfile: {
    requiredDimensions: ['completeness', 'uniqueness', 'validity', 'consistency', 'freshness'],
    thresholds: {
      completeness: 0.98,
      uniqueness: 0.95,
      validity: 0.98,
      consistency: 0.95,
      freshness: 0.90,
    },
    severity: 'HIGH',
  },
  trustProfile: {
    weights: {
      metadataCompleteness: 0.20,
      qualityScore: 0.30,
      classificationConfidence: 0.25,
      lineageAvailability: 0.15,
      reviewStatus: 0.10,
    },
    minimumScore: 75,
  },
  certificationProfile: {
    requirements: {
      qualityThreshold: 85,
      classificationReviewed: true,
      lineageAvailable: true,
      requiredMetadata: ['name', 'type', 'source', 'owner', 'classification', 'retention'],
      policyCompliant: true,
      humanApproval: true,
    },
  },
  humanOversightProfile: {
    level: 'HIGH',
    triggers: [
      'LOW_CONFIDENCE_CLASSIFICATION',
      'POLICY_VIOLATION',
      'SENSITIVE_DATA_DETECTED',
      'QUALITY_THRESHOLD_BREACH',
      'SCHEMA_CHANGE',
    ],
    priority: 'HIGH',
    requiredEvidence: [
      'CLASSIFICATION_EVIDENCE',
      'QUALITY_EVIDENCE',
      'LINEAGE_EVIDENCE',
      'POLICY_EVALUATION',
    ],
  },
  evidenceProfile: {
    requiredEvidence: [
      'SCAN_EVIDENCE',
      'CLASSIFICATION_EVIDENCE',
      'QUALITY_EVIDENCE',
      'LINEAGE_EVIDENCE',
      'POLICY_EVALUATION',
      'REVIEW_EVIDENCE',
    ],
    retentionPeriod: 2555, // 7 years
  },
  auditProfile: {
    requiredEvents: [
      'ASSET_CREATED',
      'ASSET_UPDATED',
      'CLASSIFICATION_CREATED',
      'CLASSIFICATION_REVIEWED',
      'QUALITY_CHECK',
      'POLICY_EVALUATION',
      'HUMAN_REVIEW',
      'CERTIFICATION',
    ],
    retentionPeriod: 2555, // 7 years
  },
  dashboardProfile: {
    visibleWidgets: [
      'Assets',
      'Sources',
      'Sensitive Data',
      'Quality',
      'Trust',
      'Lineage',
      'Pending Reviews',
      'Policies',
      'Evidence',
      'Audit',
      'Certification',
    ],
    priority: ['Sensitive Data', 'Pending Reviews', 'Quality', 'Policies'],
    ordering: [
      'Assets',
      'Sources',
      'Sensitive Data',
      'Quality',
      'Trust',
      'Lineage',
      'Pending Reviews',
      'Policies',
      'Evidence',
      'Audit',
      'Certification',
    ],
    terminology: {
      asset: 'Public Data Asset',
      source: 'Data Source',
      classification: 'Sensitivity Classification',
      quality: 'Data Quality',
    },
  },
  connectorProfile: {
    permittedConnectors: ['DEMO', 'POSTGRESQL'],
    restrictedConnectors: [],
  },
  terminologyProfile: {
    assetTerm: 'Public Data Asset',
    sourceTerm: 'Data Source',
    classificationTerm: 'Sensitivity Classification',
    qualityTerm: 'Data Quality',
    customTerms: {
      governance: 'Public Data Governance',
      compliance: 'Regulatory Compliance',
      steward: 'Data Steward',
    },
  },
  workflowProfile: {
    onboardingSteps: [
      'connect-source',
      'run-scan',
      'classify-sensitive-data',
      'review-classifications',
      'validate-quality',
      'establish-lineage',
      'certify-assets',
    ],
    reviewWorkflow: ['detect', 'classify', 'review', 'approve', 'certify'],
    certificationWorkflow: ['evaluate', 'review', 'approve', 'certify', 'publish'],
  },
  riskProfile: {
    riskThresholds: {
      low: 20,
      medium: 50,
      high: 75,
    },
    sensitiveDataProfile: 'STRICT',
  },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};
