// ============================================================
// BLUEPRINTS — Sector-Specific Blueprints
// ============================================================

import type { SolutionBlueprint } from './types';
import { BASE_BLUEPRINT } from './base-blueprint';

// ============================================================
// SME & Self-Employed Blueprint
// ============================================================

export const SME_SELF_EMPLOYED_BLUEPRINT: SolutionBlueprint = {
  ...BASE_BLUEPRINT,
  id: 'sme-self-employed',
  name: 'SME & Self-Employed AI/Data Governance',
  version: '1.0.0',
  description: 'Simplified governance for small businesses, micro-enterprises, and self-employed professionals',
  sector: 'SME',
  targetOrganizationType: 'Small and medium enterprises, micro-businesses, freelancers, self-employed',
  status: 'ACTIVE',
  implementationLevel: 'IMPLEMENTED',
  objectives: [
    'Guided onboarding',
    'Automatic inventory',
    'Simple classification',
    'Quality alerts',
    'Risk prioritization',
    'Evidence generation',
    'Audit trail',
    'Human review tasks',
    'Compliance-oriented dashboard',
  ],
  enabledAgents: [
    'source-discovery-agent',
    'metadata-intelligence-agent',
    'classification-agent',
    'classification-review-agent',
    'data-quality-agent',
    'trust-agent',
    'policy-agent',
    'evidence-agent',
    'audit-agent',
  ],
  requiredAgents: [
    'source-discovery-agent',
    'classification-agent',
    'data-quality-agent',
    'trust-agent',
    'evidence-agent',
    'audit-agent',
  ],
  optionalAgents: [
    'metadata-intelligence-agent',
    'classification-review-agent',
    'policy-agent',
  ],
  policyProfile: {
    enabledPolicies: ['PII_REQUIRES_REVIEW', 'LOW_QUALITY_REQUIRES_REVIEW'],
    enforcementLevel: 'ADVISORY',
  },
  classificationProfile: {
    priorityClassifications: ['PII', 'FINANCIAL', 'CONFIDENTIAL'],
    sensitivityLevels: ['PUBLIC', 'INTERNAL', 'CONFIDENTIAL'],
  },
  qualityProfile: {
    requiredDimensions: ['completeness', 'validity'],
    thresholds: {
      completeness: 0.90,
      validity: 0.90,
    },
    severity: 'MEDIUM',
  },
  trustProfile: {
    weights: {
      metadataCompleteness: 0.15,
      qualityScore: 0.35,
      classificationConfidence: 0.25,
      lineageAvailability: 0.10,
      reviewStatus: 0.15,
    },
    minimumScore: 50,
  },
  certificationProfile: {
    requirements: {
      qualityThreshold: 60,
      classificationReviewed: true,
      lineageAvailable: false,
      requiredMetadata: ['name', 'type'],
      policyCompliant: true,
      humanApproval: false,
    },
  },
  humanOversightProfile: {
    level: 'STANDARD',
    triggers: ['LOW_CONFIDENCE_CLASSIFICATION', 'SENSITIVE_DATA_DETECTED'],
    priority: 'MEDIUM',
    requiredEvidence: ['CLASSIFICATION_EVIDENCE'],
  },
  evidenceProfile: {
    requiredEvidence: ['SCAN_EVIDENCE', 'CLASSIFICATION_EVIDENCE', 'QUALITY_EVIDENCE'],
    retentionPeriod: 365,
  },
  auditProfile: {
    requiredEvents: ['ASSET_CREATED', 'CLASSIFICATION_CREATED', 'QUALITY_CHECK'],
    retentionPeriod: 730,
  },
  dashboardProfile: {
    visibleWidgets: ['Assets', 'Sensitive Data', 'Quality', 'Pending Reviews', 'Evidence'],
    priority: ['Sensitive Data', 'Pending Reviews', 'Quality'],
    ordering: ['Assets', 'Sensitive Data', 'Quality', 'Pending Reviews', 'Evidence'],
    terminology: {
      asset: 'Data',
      source: 'Where your data comes from',
      classification: 'Data type',
      quality: 'Data health',
    },
  },
  connectorProfile: {
    permittedConnectors: ['DEMO'],
    restrictedConnectors: ['POSTGRESQL'],
  },
  terminologyProfile: {
    assetTerm: 'Data',
    sourceTerm: 'Where your data comes from',
    classificationTerm: 'Data type',
    qualityTerm: 'Data health',
    customTerms: {
      governance: 'Data protection',
      compliance: 'Following the rules',
      steward: 'You',
    },
  },
  workflowProfile: {
    onboardingSteps: ['connect-first-source', 'automatic-scan', 'review-alerts'],
    reviewWorkflow: ['detect', 'alert', 'decide'],
    certificationWorkflow: ['check', 'approve'],
  },
  riskProfile: {
    riskThresholds: {
      low: 40,
      medium: 70,
      high: 85,
    },
    sensitiveDataProfile: 'STANDARD',
  },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

// ============================================================
// Technology / GenAI / RAG Blueprint
// ============================================================

export const TECHNOLOGY_GENAI_RAG_BLUEPRINT: SolutionBlueprint = {
  ...BASE_BLUEPRINT,
  id: 'technology-genai-rag',
  name: 'Technology, GenAI & RAG Governance',
  version: '1.0.0',
  description: 'Governance for technology companies building GenAI and RAG systems',
  sector: 'TECHNOLOGY',
  targetOrganizationType: 'Technology companies, AI/ML teams, GenAI startups',
  status: 'ACTIVE',
  implementationLevel: 'PARTIAL',
  objectives: [
    'Data discovery',
    'RAG resource governance',
    'Training data governance',
    'Sensitive data prevention',
    'Model input documentation',
    'Quality monitoring',
    'Lineage tracking',
    'Evidence collection',
    'Audit trail',
    'Drift preparation',
  ],
  enabledAgents: [
    'metadata-intelligence-agent',
    'classification-agent',
    'data-quality-agent',
    'lineage-agent',
    'training-data-governance-agent',
    'sensitive-data-prevention-agent',
    'rag-governance-agent',
    'model-input-documentation-agent',
    'data-drift-agent',
    'policy-agent',
    'evidence-agent',
    'audit-agent',
  ],
  requiredAgents: [
    'metadata-intelligence-agent',
    'classification-agent',
    'data-quality-agent',
    'lineage-agent',
    'evidence-agent',
    'audit-agent',
  ],
  optionalAgents: [
    'training-data-governance-agent',
    'sensitive-data-prevention-agent',
    'rag-governance-agent',
    'model-input-documentation-agent',
    'data-drift-agent',
    'policy-agent',
  ],
  policyProfile: {
    enabledPolicies: [
      'PII_REQUIRES_REVIEW',
      'TRAINING_DATA_GOVERNANCE',
      'RAG_RESOURCE_ELIGIBILITY',
      'SENSITIVE_DATA_PREVENTION',
    ],
    enforcementLevel: 'PREPARED',
  },
  classificationProfile: {
    priorityClassifications: ['PII', 'PHI', 'CONFIDENTIAL', 'TRAINING_DATA', 'RAG_RESOURCE'],
    sensitivityLevels: ['PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED'],
  },
  qualityProfile: {
    requiredDimensions: ['completeness', 'uniqueness', 'validity', 'freshness'],
    thresholds: {
      completeness: 0.95,
      uniqueness: 0.90,
      validity: 0.95,
      freshness: 0.85,
    },
    severity: 'HIGH',
  },
  trustProfile: {
    weights: {
      metadataCompleteness: 0.20,
      qualityScore: 0.25,
      classificationConfidence: 0.25,
      lineageAvailability: 0.20,
      reviewStatus: 0.10,
    },
    minimumScore: 70,
  },
  certificationProfile: {
    requirements: {
      qualityThreshold: 80,
      classificationReviewed: true,
      lineageAvailable: true,
      requiredMetadata: ['name', 'type', 'source', 'usage', 'model'],
      policyCompliant: true,
      humanApproval: true,
    },
  },
  humanOversightProfile: {
    level: 'HIGH',
    triggers: [
      'SENSITIVE_DATA_IN_TRAINING',
      'RAG_RESOURCE_INELIGIBLE',
      'DRIFT_DETECTED',
      'MODEL_INPUT_CHANGE',
    ],
    priority: 'HIGH',
    requiredEvidence: ['CLASSIFICATION_EVIDENCE', 'QUALITY_EVIDENCE', 'LINEAGE_EVIDENCE'],
  },
  evidenceProfile: {
    requiredEvidence: [
      'SCAN_EVIDENCE',
      'CLASSIFICATION_EVIDENCE',
      'QUALITY_EVIDENCE',
      'LINEAGE_EVIDENCE',
      'TRAINING_DATA_EVIDENCE',
      'RAG_GOVERNANCE_EVIDENCE',
    ],
    retentionPeriod: 1095, // 3 years
  },
  auditProfile: {
    requiredEvents: [
      'ASSET_CREATED',
      'CLASSIFICATION_CREATED',
      'QUALITY_CHECK',
      'TRAINING_DATA_USAGE',
      'RAG_RESOURCE_ACCESS',
      'DRIFT_DETECTED',
    ],
    retentionPeriod: 1095,
  },
  dashboardProfile: {
    visibleWidgets: [
      'Assets',
      'Training Data',
      'RAG Resources',
      'Sensitive Data',
      'Quality',
      'Lineage',
      'Drift',
      'Evidence',
      'Audit',
    ],
    priority: ['Training Data', 'RAG Resources', 'Sensitive Data', 'Drift'],
    ordering: [
      'Assets',
      'Training Data',
      'RAG Resources',
      'Sensitive Data',
      'Quality',
      'Lineage',
      'Drift',
      'Evidence',
      'Audit',
    ],
    terminology: {
      asset: 'Dataset',
      source: 'Data Source',
      classification: 'Data Classification',
      quality: 'Data Quality',
    },
  },
  connectorProfile: {
    permittedConnectors: ['DEMO', 'POSTGRESQL'],
    restrictedConnectors: [],
  },
  terminologyProfile: {
    assetTerm: 'Dataset',
    sourceTerm: 'Data Source',
    classificationTerm: 'Data Classification',
    qualityTerm: 'Data Quality',
    customTerms: {
      governance: 'AI/Data Governance',
      compliance: 'AI Compliance',
      steward: 'ML Engineer',
    },
  },
  workflowProfile: {
    onboardingSteps: [
      'register-datasets',
      'classify-data',
      'validate-quality',
      'establish-lineage',
      'approve-for-training',
    ],
    reviewWorkflow: ['detect', 'classify', 'validate', 'approve'],
    certificationWorkflow: ['evaluate', 'review', 'certify'],
  },
  riskProfile: {
    riskThresholds: {
      low: 25,
      medium: 60,
      high: 80,
    },
    sensitiveDataProfile: 'STRICT',
  },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

// ============================================================
// Finance & Retail Blueprint
// ============================================================

export const FINANCE_RETAIL_BLUEPRINT: SolutionBlueprint = {
  ...BASE_BLUEPRINT,
  id: 'finance-retail',
  name: 'Finance & Retail Data Governance',
  version: '1.0.0',
  description: 'Data governance for financial services and retail organizations with strict compliance',
  sector: 'FINANCE_RETAIL',
  targetOrganizationType: 'Banks, financial institutions, retail chains (e.g., Banco Santander, El Corte Inglés references)',
  status: 'ACTIVE',
  implementationLevel: 'IMPLEMENTED',
  objectives: [
    'Financial data governance',
    'Customer data governance',
    'Sensitive data detection',
    'Quality monitoring',
    'Lineage tracking',
    'Policy controls',
    'Human review',
    'Auditability',
    'Evidence collection',
    'Impact analysis',
  ],
  enabledAgents: [
    'classification-agent',
    'classification-review-agent',
    'sensitive-data-prevention-agent',
    'data-quality-agent',
    'anomaly-detection-agent',
    'lineage-agent',
    'impact-analysis-agent',
    'policy-agent',
    'evidence-agent',
    'audit-agent',
    'certification-agent',
  ],
  requiredAgents: [
    'classification-agent',
    'classification-review-agent',
    'sensitive-data-prevention-agent',
    'data-quality-agent',
    'lineage-agent',
    'impact-analysis-agent',
    'policy-agent',
    'evidence-agent',
    'audit-agent',
  ],
  optionalAgents: [
    'anomaly-detection-agent',
    'certification-agent',
  ],
  policyProfile: {
    enabledPolicies: [
      'PII_REQUIRES_REVIEW',
      'FINANCIAL_DATA_RESTRICTION',
      'CUSTOMER_DATA_PROTECTION',
      'LOW_QUALITY_REQUIRES_REVIEW',
      'MISSING_LINEAGE_WARNING',
    ],
    enforcementLevel: 'PREPARED',
  },
  classificationProfile: {
    priorityClassifications: ['PII', 'PHI', 'FINANCIAL', 'CONFIDENTIAL', 'RESTRICTED'],
    sensitivityLevels: ['PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED'],
  },
  qualityProfile: {
    requiredDimensions: ['completeness', 'uniqueness', 'validity', 'consistency'],
    thresholds: {
      completeness: 0.99,
      uniqueness: 0.98,
      validity: 0.99,
      consistency: 0.98,
    },
    severity: 'CRITICAL',
  },
  trustProfile: {
    weights: {
      metadataCompleteness: 0.15,
      qualityScore: 0.35,
      classificationConfidence: 0.30,
      lineageAvailability: 0.10,
      reviewStatus: 0.10,
    },
    minimumScore: 80,
  },
  certificationProfile: {
    requirements: {
      qualityThreshold: 90,
      classificationReviewed: true,
      lineageAvailable: true,
      requiredMetadata: ['name', 'type', 'source', 'owner', 'classification', 'retention', 'compliance'],
      policyCompliant: true,
      humanApproval: true,
    },
  },
  humanOversightProfile: {
    level: 'STRICT',
    triggers: [
      'FINANCIAL_DATA_DETECTED',
      'CUSTOMER_DATA_DETECTED',
      'LOW_CONFIDENCE_CLASSIFICATION',
      'POLICY_VIOLATION',
      'QUALITY_THRESHOLD_BREACH',
    ],
    priority: 'CRITICAL',
    requiredEvidence: [
      'CLASSIFICATION_EVIDENCE',
      'QUALITY_EVIDENCE',
      'LINEAGE_EVIDENCE',
      'POLICY_EVALUATION',
      'COMPLIANCE_EVIDENCE',
    ],
  },
  evidenceProfile: {
    requiredEvidence: [
      'SCAN_EVIDENCE',
      'CLASSIFICATION_EVIDENCE',
      'QUALITY_EVIDENCE',
      'LINEAGE_EVIDENCE',
      'POLICY_EVALUATION',
      'REVIEW_EVIDENCE',
      'COMPLIANCE_EVIDENCE',
    ],
    retentionPeriod: 3650, // 10 years
  },
  auditProfile: {
    requiredEvents: [
      'ASSET_CREATED',
      'ASSET_UPDATED',
      'CLASSIFICATION_CREATED',
      'CLASSIFICATION_REVIEWED',
      'QUALITY_CHECK',
      'POLICY_EVALUATION',
      'HUMAN_REVIEW',
      'CERTIFICATION',
      'COMPLIANCE_CHECK',
    ],
    retentionPeriod: 3650,
  },
  dashboardProfile: {
    visibleWidgets: [
      'Assets',
      'Sensitive Data',
      'Quality',
      'Lineage',
      'Pending Reviews',
      'Policies',
      'Evidence',
      'Audit',
      'Certification',
    ],
    priority: ['Sensitive Data', 'Pending Reviews', 'Quality', 'Policies'],
    ordering: [
      'Assets',
      'Sensitive Data',
      'Quality',
      'Lineage',
      'Pending Reviews',
      'Policies',
      'Evidence',
      'Audit',
      'Certification',
    ],
    terminology: {
      asset: 'Financial Data Asset',
      source: 'Data Source',
      classification: 'Sensitivity Classification',
      quality: 'Data Quality',
    },
  },
  connectorProfile: {
    permittedConnectors: ['DEMO', 'POSTGRESQL'],
    restrictedConnectors: [],
  },
  terminologyProfile: {
    assetTerm: 'Financial Data Asset',
    sourceTerm: 'Data Source',
    classificationTerm: 'Sensitivity Classification',
    qualityTerm: 'Data Quality',
    customTerms: {
      governance: 'Financial Data Governance',
      compliance: 'Regulatory Compliance',
      steward: 'Data Steward',
    },
  },
  workflowProfile: {
    onboardingSteps: [
      'connect-source',
      'run-scan',
      'classify-financial-data',
      'review-classifications',
      'validate-quality',
      'establish-lineage',
      'certify-assets',
    ],
    reviewWorkflow: ['detect', 'classify', 'review', 'approve', 'certify'],
    certificationWorkflow: ['evaluate', 'review', 'approve', 'certify', 'publish'],
  },
  riskProfile: {
    riskThresholds: {
      low: 15,
      medium: 45,
      high: 70,
    },
    sensitiveDataProfile: 'STRICT',
  },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

// ============================================================
// Enterprise Data Blueprint
// ============================================================

export const ENTERPRISE_DATA_BLUEPRINT: SolutionBlueprint = {
  ...BASE_BLUEPRINT,
  id: 'enterprise-data',
  name: 'Enterprise Data Governance at Scale',
  version: '1.0.0',
  description: 'Comprehensive data governance for large enterprises with complex data ecosystems',
  sector: 'ENTERPRISE',
  targetOrganizationType: 'Large enterprises, telecommunications, multi-national corporations (e.g., Telefónica reference)',
  status: 'ACTIVE',
  implementationLevel: 'IMPLEMENTED',
  objectives: [
    'Multi-source discovery',
    'Large asset inventories',
    'Metadata automation',
    'Schema change detection',
    'Quality monitoring',
    'Lineage tracking',
    'Impact analysis',
    'Search intelligence',
    'Business glossary',
    'Recommendations',
    'Usage analytics',
    'Governance at scale',
  ],
  enabledAgents: [
    'source-discovery-agent',
    'metadata-intelligence-agent',
    'schema-change-agent',
    'data-quality-agent',
    'anomaly-detection-agent',
    'lineage-agent',
    'impact-analysis-agent',
    'search-intelligence-agent',
    'business-glossary-agent',
    'recommendation-agent',
    'usage-analytics-agent',
    'policy-agent',
    'evidence-agent',
    'audit-agent',
  ],
  requiredAgents: [
    'source-discovery-agent',
    'metadata-intelligence-agent',
    'data-quality-agent',
    'lineage-agent',
    'impact-analysis-agent',
    'policy-agent',
    'evidence-agent',
    'audit-agent',
  ],
  optionalAgents: [
    'schema-change-agent',
    'anomaly-detection-agent',
    'search-intelligence-agent',
    'business-glossary-agent',
    'recommendation-agent',
    'usage-analytics-agent',
  ],
  policyProfile: {
    enabledPolicies: [
      'PII_REQUIRES_REVIEW',
      'LOW_QUALITY_REQUIRES_REVIEW',
      'MISSING_LINEAGE_WARNING',
      'ENTERPRISE_DATA_STANDARDS',
    ],
    enforcementLevel: 'PREPARED',
  },
  classificationProfile: {
    priorityClassifications: ['PII', 'CONFIDENTIAL', 'IDENTIFIER', 'LOCATION'],
    sensitivityLevels: ['PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED'],
  },
  qualityProfile: {
    requiredDimensions: ['completeness', 'uniqueness', 'validity', 'consistency', 'freshness'],
    thresholds: {
      completeness: 0.95,
      uniqueness: 0.92,
      validity: 0.95,
      consistency: 0.93,
      freshness: 0.88,
    },
    severity: 'HIGH',
  },
  trustProfile: {
    weights: {
      metadataCompleteness: 0.20,
      qualityScore: 0.30,
      classificationConfidence: 0.20,
      lineageAvailability: 0.20,
      reviewStatus: 0.10,
    },
    minimumScore: 70,
  },
  certificationProfile: {
    requirements: {
      qualityThreshold: 80,
      classificationReviewed: true,
      lineageAvailable: true,
      requiredMetadata: ['name', 'type', 'source', 'owner', 'domain', 'classification'],
      policyCompliant: true,
      humanApproval: true,
    },
  },
  humanOversightProfile: {
    level: 'HIGH',
    triggers: [
      'LOW_CONFIDENCE_CLASSIFICATION',
      'POLICY_VIOLATION',
      'SCHEMA_CHANGE',
      'QUALITY_THRESHOLD_BREACH',
    ],
    priority: 'HIGH',
    requiredEvidence: ['CLASSIFICATION_EVIDENCE', 'QUALITY_EVIDENCE', 'LINEAGE_EVIDENCE'],
  },
  evidenceProfile: {
    requiredEvidence: [
      'SCAN_EVIDENCE',
      'CLASSIFICATION_EVIDENCE',
      'QUALITY_EVIDENCE',
      'LINEAGE_EVIDENCE',
      'POLICY_EVALUATION',
    ],
    retentionPeriod: 1825, // 5 years
  },
  auditProfile: {
    requiredEvents: [
      'ASSET_CREATED',
      'ASSET_UPDATED',
      'CLASSIFICATION_CREATED',
      'QUALITY_CHECK',
      'POLICY_EVALUATION',
      'SCHEMA_CHANGE',
    ],
    retentionPeriod: 1825,
  },
  dashboardProfile: {
    visibleWidgets: [
      'Assets',
      'Sources',
      'Quality',
      'Trust',
      'Lineage',
      'Pending Reviews',
      'Policies',
      'Evidence',
      'Audit',
      'Agent Operations',
    ],
    priority: ['Quality', 'Lineage', 'Agent Operations'],
    ordering: [
      'Assets',
      'Sources',
      'Quality',
      'Trust',
      'Lineage',
      'Pending Reviews',
      'Policies',
      'Evidence',
      'Audit',
      'Agent Operations',
    ],
    terminology: {
      asset: 'Enterprise Data Asset',
      source: 'Data Source',
      classification: 'Classification',
      quality: 'Quality',
    },
  },
  connectorProfile: {
    permittedConnectors: ['DEMO', 'POSTGRESQL'],
    restrictedConnectors: [],
  },
  terminologyProfile: {
    assetTerm: 'Enterprise Data Asset',
    sourceTerm: 'Data Source',
    classificationTerm: 'Classification',
    qualityTerm: 'Quality',
    customTerms: {
      governance: 'Enterprise Data Governance',
      compliance: 'Compliance',
      steward: 'Data Steward',
    },
  },
  workflowProfile: {
    onboardingSteps: [
      'discover-sources',
      'scan-assets',
      'classify-data',
      'validate-quality',
      'establish-lineage',
      'publish-glossary',
    ],
    reviewWorkflow: ['detect', 'classify', 'review', 'approve'],
    certificationWorkflow: ['evaluate', 'review', 'certify'],
  },
  riskProfile: {
    riskThresholds: {
      low: 25,
      medium: 55,
      high: 75,
    },
    sensitiveDataProfile: 'STRICT',
  },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

// ============================================================
// Research / MLOps Blueprint
// ============================================================

export const RESEARCH_MLOPS_BLUEPRINT: SolutionBlueprint = {
  ...BASE_BLUEPRINT,
  id: 'research-mlops',
  name: 'Research, Data Science & MLOps Governance',
  version: '1.0.0',
  description: 'Governance for research institutions and MLOps teams focused on reproducibility and traceability',
  sector: 'RESEARCH',
  targetOrganizationType: 'Research institutions, data science teams, MLOps organizations (e.g., BSC-CNS reference)',
  status: 'ACTIVE',
  implementationLevel: 'PARTIAL',
  objectives: [
    'Dataset discovery',
    'Dataset versioning',
    'Training data traceability',
    'Quality snapshots',
    'Classification snapshots',
    'Lineage tracking',
    'Certification',
    'Model input documentation',
    'Data drift',
    'Reproducibility',
    'Evidence collection',
    'Audit trail',
  ],
  enabledAgents: [
    'metadata-intelligence-agent',
    'classification-agent',
    'data-quality-agent',
    'lineage-agent',
    'training-data-governance-agent',
    'sensitive-data-prevention-agent',
    'model-input-documentation-agent',
    'data-drift-agent',
    'certification-agent',
    'evidence-agent',
    'audit-agent',
  ],
  requiredAgents: [
    'metadata-intelligence-agent',
    'classification-agent',
    'data-quality-agent',
    'lineage-agent',
    'evidence-agent',
    'audit-agent',
  ],
  optionalAgents: [
    'training-data-governance-agent',
    'sensitive-data-prevention-agent',
    'model-input-documentation-agent',
    'data-drift-agent',
    'certification-agent',
  ],
  policyProfile: {
    enabledPolicies: [
      'PII_REQUIRES_REVIEW',
      'TRAINING_DATA_GOVERNANCE',
      'REPRODUCIBILITY_REQUIREMENT',
    ],
    enforcementLevel: 'PREPARED',
  },
  classificationProfile: {
    priorityClassifications: ['PII', 'PHI', 'TRAINING_DATA', 'RESEARCH_DATA'],
    sensitivityLevels: ['PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED'],
  },
  qualityProfile: {
    requiredDimensions: ['completeness', 'uniqueness', 'validity', 'consistency'],
    thresholds: {
      completeness: 0.95,
      uniqueness: 0.90,
      validity: 0.95,
      consistency: 0.92,
    },
    severity: 'HIGH',
  },
  trustProfile: {
    weights: {
      metadataCompleteness: 0.25,
      qualityScore: 0.25,
      classificationConfidence: 0.20,
      lineageAvailability: 0.20,
      reviewStatus: 0.10,
    },
    minimumScore: 75,
  },
  certificationProfile: {
    requirements: {
      qualityThreshold: 85,
      classificationReviewed: true,
      lineageAvailable: true,
      requiredMetadata: ['name', 'type', 'source', 'version', 'usage', 'model'],
      policyCompliant: true,
      humanApproval: true,
    },
  },
  humanOversightProfile: {
    level: 'HIGH',
    triggers: [
      'TRAINING_DATA_CHANGE',
      'DRIFT_DETECTED',
      'REPRODUCIBILITY_ISSUE',
      'SENSITIVE_DATA_IN_DATASET',
    ],
    priority: 'HIGH',
    requiredEvidence: ['CLASSIFICATION_EVIDENCE', 'QUALITY_EVIDENCE', 'LINEAGE_EVIDENCE'],
  },
  evidenceProfile: {
    requiredEvidence: [
      'SCAN_EVIDENCE',
      'CLASSIFICATION_EVIDENCE',
      'QUALITY_EVIDENCE',
      'LINEAGE_EVIDENCE',
      'TRAINING_DATA_EVIDENCE',
      'DRIFT_EVIDENCE',
    ],
    retentionPeriod: 1825, // 5 years
  },
  auditProfile: {
    requiredEvents: [
      'ASSET_CREATED',
      'DATASET_VERSIONED',
      'CLASSIFICATION_CREATED',
      'QUALITY_CHECK',
      'TRAINING_DATA_USAGE',
      'DRIFT_DETECTED',
    ],
    retentionPeriod: 1825,
  },
  dashboardProfile: {
    visibleWidgets: [
      'Assets',
      'Training Data',
      'Quality',
      'Lineage',
      'Drift',
      'Certification',
      'Evidence',
      'Audit',
    ],
    priority: ['Training Data', 'Drift', 'Quality'],
    ordering: [
      'Assets',
      'Training Data',
      'Quality',
      'Lineage',
      'Drift',
      'Certification',
      'Evidence',
      'Audit',
    ],
    terminology: {
      asset: 'Dataset',
      source: 'Data Source',
      classification: 'Data Classification',
      quality: 'Data Quality',
    },
  },
  connectorProfile: {
    permittedConnectors: ['DEMO', 'POSTGRESQL'],
    restrictedConnectors: [],
  },
  terminologyProfile: {
    assetTerm: 'Dataset',
    sourceTerm: 'Data Source',
    classificationTerm: 'Data Classification',
    qualityTerm: 'Data Quality',
    customTerms: {
      governance: 'Research Data Governance',
      compliance: 'Research Compliance',
      steward: 'Data Scientist',
    },
  },
  workflowProfile: {
    onboardingSteps: [
      'register-dataset',
      'version-data',
      'classify-data',
      'validate-quality',
      'document-lineage',
      'certify-dataset',
    ],
    reviewWorkflow: ['detect', 'classify', 'validate', 'approve'],
    certificationWorkflow: ['evaluate', 'review', 'certify'],
  },
  riskProfile: {
    riskThresholds: {
      low: 30,
      medium: 60,
      high: 80,
    },
    sensitiveDataProfile: 'STRICT',
  },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};
