// ============================================================
// PAGES — Audit
// ============================================================

import { useState, useMemo } from 'react';
import { useCatalog } from '../app/CatalogContext';
import { Card, Badge, EmptyState, DemoBanner } from '../components/ui';
import { formatDate, timeAgo } from '../lib/utils';
import type { AuditAction } from '../types';

const AUDIT_ACTIONS: AuditAction[] = ['CREATE', 'UPDATE', 'DELETE', 'SCAN', 'CLASSIFY', 'REVIEW', 'CONNECT'];

export function AuditPage() {
  const { auditEvents } = useCatalog();
  const [actionFilter, setActionFilter] = useState<string>('');
  const [resourceFilter, setResourceFilter] = useState<string>('');

  const resourceTypes = useMemo(() => {
    const types = new Set(auditEvents.map(e => e.resourceType));
    return Array.from(types);
  }, [auditEvents]);

  const filtered = useMemo(() => {
    let result = auditEvents;
    if (actionFilter) {
      result = result.filter(e => e.action === actionFilter);
    }
    if (resourceFilter) {
      result = result.filter(e => e.resourceType === resourceFilter);
    }
    return result;
  }, [auditEvents, actionFilter, resourceFilter]);

  const getActionBadge = (action: AuditAction) => {
    switch (action) {
      case 'CREATE': return 'success';
      case 'UPDATE': return 'info';
      case 'DELETE': return 'danger';
      case 'SCAN': return 'demo';
      case 'CLASSIFY': return 'warning';
      case 'REVIEW': return 'info';
      case 'CONNECT': return 'default';
      default: return 'default';
    }
  };

  return (
    <div className="space-y-6">
      <DemoBanner />

      <div>
        <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">Audit Trail</h2>
        <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
          Chronological record of all system and user activities.
        </p>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap gap-3 items-center">
        <div className="flex flex-wrap gap-1">
          <button
            onClick={() => setActionFilter('')}
            className={`px-2.5 py-1 rounded text-xs font-medium transition-colors ${
              !actionFilter ? 'bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-200' : 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400 hover:bg-gray-200'
            }`}
          >
            All Actions
          </button>
          {AUDIT_ACTIONS.map(action => (
            <button
              key={action}
              onClick={() => setActionFilter(action === actionFilter ? '' : action)}
              className={`px-2.5 py-1 rounded text-xs font-medium transition-colors ${
                action === actionFilter ? 'bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-200' : 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400 hover:bg-gray-200'
              }`}
            >
              {action}
            </button>
          ))}
        </div>
        <select
          value={resourceFilter}
          onChange={e => setResourceFilter(e.target.value)}
          className="px-3 py-1.5 border border-gray-300 dark:border-gray-600 rounded-md text-xs bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100"
        >
          <option value="">All Resources</option>
          {resourceTypes.map(type => (
            <option key={type} value={type}>{type}</option>
          ))}
        </select>
        <span className="text-xs text-gray-400 ml-auto">
          {filtered.length} event{filtered.length !== 1 ? 's' : ''}
        </span>
      </div>

      {/* Events */}
      {filtered.length === 0 ? (
        <Card>
          <EmptyState
            title="No audit events"
            description="Audit events are generated by all system operations including scans, classifications, and user actions."
          />
        </Card>
      ) : (
        <Card>
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
              <thead className="bg-gray-50 dark:bg-gray-800">
                <tr>
                  <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Timestamp</th>
                  <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Action</th>
                  <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Resource</th>
                  <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Actor</th>
                  <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Details</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
                {filtered.map(event => (
                  <tr key={event.id} className="hover:bg-gray-50 dark:hover:bg-gray-800">
                    <td className="px-4 py-2 text-xs text-gray-500 dark:text-gray-400 whitespace-nowrap">
                      <div>{formatDate(event.timestamp)}</div>
                      <div className="text-gray-400">{timeAgo(event.timestamp)}</div>
                    </td>
                    <td className="px-4 py-2">
                      <Badge variant={getActionBadge(event.action) as 'success' | 'info' | 'danger' | 'demo' | 'warning' | 'default'}>
                        {event.action}
                      </Badge>
                    </td>
                    <td className="px-4 py-2 text-sm">
                      <span className="text-gray-700 dark:text-gray-300">{event.resourceType}</span>
                      <span className="text-xs text-gray-400 ml-1 font-mono">{event.resourceId.slice(0, 8)}...</span>
                    </td>
                    <td className="px-4 py-2 text-xs text-gray-500 dark:text-gray-400">
                      {event.actor}
                    </td>
                    <td className="px-4 py-2 text-xs text-gray-400 max-w-xs truncate">
                      {event.details ? JSON.stringify(event.details) : '—'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>
      )}
    </div>
  );
}
