// ============================================================
// PAGES — Evidence
// ============================================================

import { useState, useMemo } from 'react';
import { useCatalog } from '../app/CatalogContext';
import { Card, Badge, EmptyState, DemoBanner } from '../components/ui';
import { formatDate, timeAgo } from '../lib/utils';
import type { EvidenceType } from '../types';

const EVIDENCE_TYPES: EvidenceType[] = [
  'SOURCE_CREATED',
  'SOURCE_UPDATED',
  'SCAN_COMPLETED',
  'SCAN_FAILED',
  'ASSET_DISCOVERED',
  'ASSET_UPDATED',
  'CLASSIFICATION_CREATED',
  'CLASSIFICATION_REVIEWED',
  'QUALITY_CHECK_COMPLETED',
  'CONNECTION_TESTED',
];

export function EvidencePage() {
  const { evidence } = useCatalog();
  const [typeFilter, setTypeFilter] = useState<string>('');
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const filtered = useMemo(() => {
    if (!typeFilter) return evidence;
    return evidence.filter(e => e.type === typeFilter);
  }, [evidence, typeFilter]);

  // Count by type
  const counts = useMemo(() => {
    const map: Record<string, number> = {};
    for (const e of evidence) {
      map[e.type] = (map[e.type] ?? 0) + 1;
    }
    return map;
  }, [evidence]);

  return (
    <div className="space-y-6">
      <DemoBanner />

      <div>
        <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">Evidence Records</h2>
        <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
          Proof records generated by system operations. Each evidence record documents a relevant state or process outcome.
        </p>
      </div>

      {/* Summary */}
      <div className="flex flex-wrap gap-2">
        <button
          onClick={() => setTypeFilter('')}
          className={`px-2.5 py-1 rounded text-xs font-medium transition-colors ${
            !typeFilter ? 'bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-200' : 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400 hover:bg-gray-200'
          }`}
        >
          All ({evidence.length})
        </button>
        {EVIDENCE_TYPES.filter(t => counts[t]).map(type => (
          <button
            key={type}
            onClick={() => setTypeFilter(type === typeFilter ? '' : type)}
            className={`px-2.5 py-1 rounded text-xs font-medium transition-colors ${
              type === typeFilter ? 'bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-200' : 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400 hover:bg-gray-200'
            }`}
          >
            {type} ({counts[type]})
          </button>
        ))}
      </div>

      {/* Evidence List */}
      {filtered.length === 0 ? (
        <Card>
          <EmptyState
            title="No evidence records"
            description="Evidence records are generated during scan, classification, and quality operations."
          />
        </Card>
      ) : (
        <div className="space-y-2">
          {filtered.map(ev => (
            <Card key={ev.id} className="!p-0">
              <div
                className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
                onClick={() => setExpandedId(expandedId === ev.id ? null : ev.id)}
              >
                <div className="flex items-center gap-3">
                  <Badge variant="info">{ev.type}</Badge>
                  <div>
                    <span className="text-sm text-gray-700 dark:text-gray-300">{ev.subjectType}</span>
                    <span className="text-xs text-gray-400 ml-2 font-mono">{ev.subjectId.slice(0, 8)}...</span>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <span className="text-xs text-gray-400">{ev.actor}</span>
                  <span className="text-xs text-gray-400">{timeAgo(ev.timestamp)}</span>
                  <svg
                    className={`w-4 h-4 text-gray-400 transition-transform ${expandedId === ev.id ? 'rotate-180' : ''}`}
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                  </svg>
                </div>
              </div>
              {expandedId === ev.id && (
                <div className="px-4 py-3 border-t border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50">
                  <dl className="grid grid-cols-2 gap-2 text-xs">
                    <div>
                      <dt className="text-gray-500">ID</dt>
                      <dd className="font-mono text-gray-700 dark:text-gray-300">{ev.id}</dd>
                    </div>
                    <div>
                      <dt className="text-gray-500">Timestamp</dt>
                      <dd className="text-gray-700 dark:text-gray-300">{formatDate(ev.timestamp)}</dd>
                    </div>
                    <div>
                      <dt className="text-gray-500">Actor</dt>
                      <dd className="text-gray-700 dark:text-gray-300">{ev.actor}</dd>
                    </div>
                    <div>
                      <dt className="text-gray-500">Source</dt>
                      <dd className="text-gray-700 dark:text-gray-300">{ev.source}</dd>
                    </div>
                  </dl>
                  {ev.metadata && Object.keys(ev.metadata).length > 0 && (
                    <div className="mt-3">
                      <dt className="text-xs text-gray-500 mb-1">Metadata</dt>
                      <pre className="text-xs text-gray-600 dark:text-gray-400 bg-white dark:bg-gray-900 p-3 rounded border border-gray-200 dark:border-gray-700 overflow-x-auto">
                        {JSON.stringify(ev.metadata, null, 2)}
                      </pre>
                    </div>
                  )}
                </div>
              )}
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
